/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package personal_library_management;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author frabbi
 */
public class Personal_Library_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Personal_Library_GUI
     */
    public Personal_Library_GUI() {
        initComponents();
//        ShowAllBook();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        Ledition = new javax.swing.JLabel();
        Lwritername = new javax.swing.JLabel();
        Lcatagory = new javax.swing.JLabel();
        Lpublisher = new javax.swing.JLabel();
        edition = new javax.swing.JTextField();
        wName = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        Lbookname = new javax.swing.JLabel();
        bName = new javax.swing.JTextField();
        exitbt = new javax.swing.JButton();
        Lisbn = new javax.swing.JLabel();
        editor = new javax.swing.JLabel();
        editorT = new javax.swing.JTextField();
        showbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showtableGUI = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        srctext = new javax.swing.JTextField();
        srchbtn = new javax.swing.JButton();
        isbnT = new javax.swing.JTextField();
        bCat = new javax.swing.JComboBox();
        publisherT = new javax.swing.JTextField();
        lendbook = new javax.swing.JButton();
        srccombo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Manager");
        setBackground(new java.awt.Color(105, 121, 125));

        jPanel1.setBackground(new java.awt.Color(202, 215, 192));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12), new java.awt.Color(173, 134, 134))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(223, 223, 238));

        Ledition.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        Ledition.setText("Edition");

        Lwritername.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        Lwritername.setText("Author");

        Lcatagory.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        Lcatagory.setText("Catagory");

        Lpublisher.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        Lpublisher.setText("Publisher");

        edition.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N

        wName.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N

        savebtn.setText("SAVE");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        Lbookname.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        Lbookname.setText("Book Name");

        bName.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N

        exitbt.setText("EXIT");
        exitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtActionPerformed(evt);
            }
        });

        Lisbn.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        Lisbn.setText("ISBN");

        editor.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        editor.setText("Editor");

        editorT.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N

        showbtn.setText("SHOW");
        showbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbtnActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N

        showtableGUI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showtableGUI.setFont(new java.awt.Font("Dialog", 2, 13)); // NOI18N
        showtableGUI.setForeground(new java.awt.Color(59, 116, 122));
        showtableGUI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index No", "Book Name", "Edition", "Author", "Editor", "Catagory", "Publisher", "ISBN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showtableGUI.setGridColor(new java.awt.Color(53, 106, 156));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, showtableGUI, org.jdesktop.beansbinding.ObjectProperty.create(), showtableGUI, org.jdesktop.beansbinding.BeanProperty.create("selectedElements"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(showtableGUI);
        if (showtableGUI.getColumnModel().getColumnCount() > 0) {
            showtableGUI.getColumnModel().getColumn(0).setResizable(false);
            showtableGUI.getColumnModel().getColumn(1).setResizable(false);
            showtableGUI.getColumnModel().getColumn(2).setResizable(false);
            showtableGUI.getColumnModel().getColumn(3).setResizable(false);
            showtableGUI.getColumnModel().getColumn(4).setResizable(false);
            showtableGUI.getColumnModel().getColumn(5).setResizable(false);
            showtableGUI.getColumnModel().getColumn(6).setResizable(false);
            showtableGUI.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 108, 47));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERSONAL BOOK MANAGER");

        srctext.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N

        srchbtn.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        srchbtn.setText("SEARCH");
        srchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchbtnActionPerformed(evt);
            }
        });

        isbnT.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N

        bCat.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        bCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Qur'an", "Hadith", "Islami Book", "Engineering", "Novel", "Fiction", "Science Fiction", "Programming", "Literature ", "History" }));

        publisherT.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N

        lendbook.setText("LEND TO");
        lendbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendbookActionPerformed(evt);
            }
        });

        srccombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Book Name", "Author" }));

        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        del.setText("DELETE");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ledition)
                            .addComponent(Lwritername)
                            .addComponent(Lcatagory, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbookname)
                            .addComponent(editor)
                            .addComponent(Lpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lisbn))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(isbnT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(publisherT, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(editorT, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(wName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(edition, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bName, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(savebtn)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(showbtn)
                                .addGap(18, 18, 18)
                                .addComponent(del)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(lendbook)
                                .addGap(18, 18, 18)
                                .addComponent(exitbt))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(srccombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(srctext, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(srchbtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbookname)
                    .addComponent(bName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srctext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srchbtn)
                    .addComponent(srccombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ledition)
                            .addComponent(edition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lwritername)
                            .addComponent(wName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editor)
                            .addComponent(editorT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lcatagory)
                            .addComponent(bCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lpublisher)
                            .addComponent(publisherT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lisbn)
                            .addComponent(isbnT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitbt)
                    .addComponent(del)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(savebtn)
                        .addComponent(showbtn)
                        .addComponent(jButton1)
                        .addComponent(lendbook)
                        .addComponent(jButton3)))
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    Book book = new Book();
    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        Object part = evt.getSource();
        if(part == savebtn)
        {
            savebtn.setEnabled(true);
        }
        try{
            //mysql connection
            String userName = "root";
            String password = "";
            String url      = "jdbc:mysql://localhost:3306/personal_Book_Manager";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection(url, userName, password);
            Statement st    = con.createStatement();
            
            //GUI input
           
            book.bookName       = bName.getText(); //book name
            book.edition        = edition.getText();  //edition
            book.authorName     = wName.getText();//writer name
            book.editor         = editorT.getText();// editor name
            book.bookCategory    = (String)bCat.getSelectedItem();//book's catagory
            book.publication     = publisherT.getText(); //publisher name
            book.isbn            = isbnT.getText(); //internation standard book number
                      
            //mysql query for insert            
//            String insertStr = "";
//            insertStr = "INSERT INTO book_lists(Book_Name, Edition, Writer_Name, Editor, Catagory, Publisher, ISBN) "
//                    + "VALUES ('"+bookname+"','"+editn+"','"+writername+"','"+editr+"','"+bookcat+"','"+pub+"','"+isbn+"')";
            
//            st.execute(insertStr);
            
//           ShowAllBook();
            
            JOptionPane.showMessageDialog(rootPane, "Succesfully INSERTED");
            
        } 
        catch(Exception e )
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void exitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtActionPerformed
        // TODO add your handling code here:
      exitbt.addActionListener(new ActionListener() {
          

          @Override
          public void actionPerformed(ActionEvent e) {
              System.exit(0);
          }
      }
              );
    }//GEN-LAST:event_exitbtActionPerformed

    private void showbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbtnActionPerformed
        // TODO add your handling code here:
        Object part = evt.getSource();
        if(part == showbtn)
        {
            showbtn.setEnabled(true);
        }
//        try
//        {
//            //mysql connection
//            String userName = "root";
//            String password = "";
//            String url      = "jdbc:mysql://localhost:3306/personal_Book_Manager";
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con  = DriverManager.getConnection(url, userName, password);
//            Statement st    = con.createStatement();
//            
//            // query for show table on interface....
//           ShowAllBook();
//        }
//        catch(Exception e)
//        {
//          e.printStackTrace();
//        }
    }//GEN-LAST:event_showbtnActionPerformed

//    private void ShowAllBook()
//    {
//        try
//        {
//            //mysql connection
//            String userName = "root";
//            String password = "";
//            String url      = "jdbc:mysql://localhost:3306/personal_Book_Manager";
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con  = DriverManager.getConnection(url, userName, password);
//            Statement st    = con.createStatement();
//            
//            // query for show table on interface....
//            String showtable = "select *from book_lists";
//            ResultSet rs = st.executeQuery(showtable);
//            
//            showtableGUI.setModel(DbUtils.resultSetToTableModel(rs));
//        }
//        catch(Exception e)
//        {
//          e.printStackTrace();
//        }
//    }
    private void srchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchbtnActionPerformed
        // TODO add your handling code here:
        Object part = evt.getSource();
        if(part == srchbtn)
        {
            srchbtn.setEnabled(true);
        }
        
        try
        {
            String userName = "root";
            String password = "";
            String url      = "jdbc:mysql://localhost:3306/personal_Book_Manager";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection(url, userName, password);
            
            String src = srctext.getText();
            String combo    = (String)srccombo.getSelectedItem();
            
            //specific search
            if("Book Name".equals(combo))
            {
                String searchstuff= "SELECT  *from book_lists where Book_Name LIKE '"+'%'+src+'%'+"'";
                PreparedStatement st    = con.prepareStatement(searchstuff); 
                ResultSet ps = st.executeQuery(searchstuff);
                showtableGUI.setModel(DbUtils.resultSetToTableModel(ps));
            }
            else /*if("Author".equals(combo))*/
            {
                String searchstuff= "SELECT  *from book_lists where Writer_Name LIKE '"+'%'+src+'%'+"'";
                PreparedStatement st    = con.prepareStatement(searchstuff); 
                ResultSet ps = st.executeQuery(searchstuff);
                showtableGUI.setModel(DbUtils.resultSetToTableModel(ps));
            }            
        }
        catch(Exception v)
        {
            JOptionPane.showMessageDialog(null, "Unable to Search");
            v.printStackTrace();
        }
        
    }//GEN-LAST:event_srchbtnActionPerformed

    private void lendbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendbookActionPerformed
        // TODO add your handling code here:
       
      personal_library_GUI2 sh= new personal_library_GUI2();
      sh.setVisible(true);
    }//GEN-LAST:event_lendbookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        bName.setText(" ");
        editorT.setText("");
        edition.setText("");
        wName.setText("");
        publisherT.setText("");
        isbnT.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        Object part = evt.getSource();
        if(part == del)
        {
            del.setEnabled(true);
        }
        
         //book name
        int row = showtableGUI.getSelectedRow();
        if(row<0) return; 
        String bookname   = showtableGUI.getValueAt(row, 0).toString();
        DefaultTableModel model = (DefaultTableModel)showtableGUI.getModel();
            
           // String selected = model.getValueAt(row, 3).toString();
            
           
        try
        {
            //mysql connection
            String userName = "root";
            String password = "";
            String url      = "jdbc:mysql://localhost:3306/personal_Book_Manager";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection(url, userName, password);
            
            String sql = "DELETE FROM book_lists WHERE Book_Name='"+bookname+"'";
            System.out.println(sql);
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            model.removeRow(showtableGUI.getSelectedRow());
            JOptionPane.showMessageDialog(null, "DONE");
           
        }
        catch(HeadlessException dd)
        {
        } catch (ClassNotFoundException dd) {
        } catch (SQLException dd) {
        }
    }//GEN-LAST:event_delActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personal_Library_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personal_Library_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personal_Library_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personal_Library_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Personal_Library_GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbookname;
    private javax.swing.JLabel Lcatagory;
    private javax.swing.JLabel Ledition;
    private javax.swing.JLabel Lisbn;
    private javax.swing.JLabel Lpublisher;
    private javax.swing.JLabel Lwritername;
    private javax.swing.JComboBox bCat;
    private javax.swing.JTextField bName;
    private javax.swing.JButton del;
    private javax.swing.JTextField edition;
    private javax.swing.JLabel editor;
    private javax.swing.JTextField editorT;
    private javax.swing.JButton exitbt;
    private javax.swing.JTextField isbnT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lendbook;
    private javax.swing.JTextField publisherT;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton showbtn;
    private javax.swing.JTable showtableGUI;
    private javax.swing.JComboBox srccombo;
    private javax.swing.JButton srchbtn;
    private javax.swing.JTextField srctext;
    private javax.swing.JTextField wName;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
