/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package personal_library_management;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author frabbi
 */
public class personal_library_GUI2 extends javax.swing.JFrame {

    /**
     * Creates new form personal_library_GUI2
     */
    TreeMap<String, String> ba;
    public personal_library_GUI2() {
        initComponents();
        ShowAllBorrowers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backdate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namet = new javax.swing.JTextField();
        authort = new javax.swing.JTextField();
        e_mail = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lendtable = new javax.swing.JTable();
        exitbtn = new javax.swing.JButton();
        showbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        srct = new javax.swing.JTextField();
        srcbtn = new javax.swing.JButton();
        combot = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        phn_no = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        issuedate = new com.toedter.calendar.JDateChooser();
        returndate = new com.toedter.calendar.JDateChooser();
        bCat = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        bCat1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Book category :");

        jLabel3.setText("Author");

        jLabel4.setText("E-Mail");

        authort.setEditable(false);

        savebtn.setText("SAVE");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        lendtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Book Name", "Author", "E-Mail", "Phone No.", "Issue Date", "Back Date", "Fine"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lendtable);

        exitbtn.setText("EXIT");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        showbtn.setText("SHOW");
        showbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel5.setText("LEND BOOKS");

        srcbtn.setText("SEARCH");
        srcbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcbtnActionPerformed(evt);
            }
        });

        combot.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "Book Name", "Author" }));

        jLabel6.setText("Phone No.");

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");

        jLabel7.setText("Issue Date");

        jLabel8.setText("Return Date");

        bCat.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        bCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Qur'an", "Hadith", "Islami Book", "Engineering", "Novel", "Fiction", "Science Fiction", "Programming", "Literature ", "History" }));
        bCat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bCatItemStateChanged(evt);
            }
        });

        jLabel9.setText("Book name :");

        bCat1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        bCat1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--" }));
        bCat1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bCat1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout backdateLayout = new javax.swing.GroupLayout(backdate);
        backdate.setLayout(backdateLayout);
        backdateLayout.setHorizontalGroup(
            backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backdateLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backdateLayout.createSequentialGroup()
                        .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(58, 58, 58)
                        .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namet, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(authort, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(e_mail, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(phn_no)
                            .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(savebtn))
                .addGap(58, 58, 58)
                .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backdateLayout.createSequentialGroup()
                        .addComponent(showbtn)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(11, 11, 11)
                        .addComponent(exitbtn))
                    .addGroup(backdateLayout.createSequentialGroup()
                        .addComponent(combot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(srct, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(srcbtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(backdateLayout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backdateLayout.setVerticalGroup(
            backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(namet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srcbtn)
                    .addComponent(combot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backdateLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(145, Short.MAX_VALUE))
                    .addGroup(backdateLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(bCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(bCat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(authort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(e_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(phn_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backdateLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(exitbtn)
                                    .addComponent(showbtn)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)
                                    .addComponent(savebtn))
                                .addGap(76, 76, 76))
                            .addGroup(backdateLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(backdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backdateLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel8))
                                    .addGroup(backdateLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(returndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        Object part = evt.getSource();
        if(part == savebtn)
        {
            savebtn.setEnabled(true);
        }      
        if(bCat1.getSelectedIndex()<=0) return;
        try
        {
            String userName = "root";
            String password = "";
            String url      = "jdbc:mysql://localhost:3306/personal_Book_Manager";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection(url, userName, password);
            Statement st    = con.createStatement();
            
            String name     =  namet.getText();
            String bname    =  bCat1.getSelectedItem().toString();
            String author   =  authort.getText();
            String email    =  e_mail.getText();
            String phn      =  phn_no.getText();
            String idate    =  ((JTextField)issuedate.getDateEditor().getUiComponent()).getText();
            String bdate    =  ((JTextField)returndate.getDateEditor().getUiComponent()).getText();
            
            String insertto = "";
            insertto = "INSERT INTO borrowers_list (Name, Book_Name, Author,E_Mail, Phone_No, Issue_Date, Back_Date)"
                    + "values('"+name+"','"+bname+"','"+author+"','"+email+"','"+phn+"','"+idate+"','"+bdate+"')";
            st.execute(insertto);
            JOptionPane.showMessageDialog(null, "Successfully inserted");
            
            ShowAllBorrowers();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Got exception");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_savebtnActionPerformed

    private void ShowAllBorrowers()
    {
        try
        {
            //mysql connection
            String userName = "root";
            String password = "";
            String url      = "jdbc:mysql://localhost:3306/personal_Book_Manager";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection(url, userName, password);
            Statement st    = con.createStatement();
            
            // query for show table on interface....
            String showtable = "select *from borrowers_list";
            ResultSet rs = st.executeQuery(showtable);
            
            lendtable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
          e.printStackTrace();
        }
    }
    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        exitbtn.addActionListener(new ActionListener() {         

          @Override
          public void actionPerformed(ActionEvent e) {
              System.exit(0);
              //hrow new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
          }
      }
              );
    }//GEN-LAST:event_exitbtnActionPerformed

    private void showbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbtnActionPerformed
        // TODO add your handling code here:
        Object part = evt.getSource();
        if(part == showbtn)
        {
            showbtn.setEnabled(true);
        }
            ShowAllBorrowers();
            
           
    }//GEN-LAST:event_showbtnActionPerformed

    private void srcbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcbtnActionPerformed
        // TODO add your handling code here:
        Object part = evt.getSource();
        if(part == srcbtn)
        {
            srcbtn.setEnabled(true);
        }
        
        
        try
        {
            String userName = "root";
            String password = "";
            String url      = "jdbc:mysql://localhost:3306/personal_Book_Manager";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection(url, userName, password);
            Statement st    = con.createStatement();
            
            String search   = srct.getText();
            String combo    = (String) combot.getSelectedItem();
            
//            String showtable = "SELECT *from lend_books where Name like '"+'%'+search+'%'+"'";
//            ResultSet rs   = st.executeQuery(showtable);
//            lendtable.setModel(DbUtils.resultSetToTableModel(rs));
            
            if("Name".equals(combo))
            {
                String showtable = "SELECT *from borrowers_list where Name like '"+'%'+search+'%'+"'";
                ResultSet rs   = st.executeQuery(showtable);
                lendtable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else if ("Book Name".equals(combo))
                    {                        
                         String showtable = "SELECT *from borrowers_list where Book_Name like '"+'%'+search+'%'+"'";
                         ResultSet rs   = st.executeQuery(showtable);
                         lendtable.setModel(DbUtils.resultSetToTableModel(rs));
                    }
            else
            {                
                String showtable = "SELECT *from borrowers_list where Author like '"+'%'+search+'%'+"'";
                ResultSet rs   = st.executeQuery(showtable);
                lendtable.setModel(DbUtils.resultSetToTableModel(rs));
            }
        }
        catch(Exception s)
        {
            s.printStackTrace();
        }
    }//GEN-LAST:event_srcbtnActionPerformed

    private void bCatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bCatItemStateChanged
        try {
            // TODO add your handling code here:
            String userName = "root";
            String password = "";
            String url      = "jdbc:mysql://localhost:3306/personal_Book_Manager";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection(url, userName, password);
            Statement st    = con.createStatement();
            String cat = bCat.getSelectedItem().toString();
            String q = "select Book_Name,Writer_Name from book_lists where Catagory = '"+cat+"'";
            String model ="--Select--";
            ba = new TreeMap<String, String>();
            ResultSet res = st.executeQuery(q);
            while(res.next())
            {
                model+=","+res.getString(1);
                ba.put(res.getString(1), res.getString(2));
            }
            bCat1.setModel(new DefaultComboBoxModel(model.split(",")));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(personal_library_GUI2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(personal_library_GUI2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCatItemStateChanged

    private void bCat1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bCat1ItemStateChanged
        // TODO add your handling code here:
        String book = bCat1.getSelectedItem().toString();
        authort.setText(ba.get(book));
    }//GEN-LAST:event_bCat1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = lendtable.getSelectedRow();
        if(row<0) return; 
        String bookname   = lendtable.getValueAt(row, 0).toString();
        DefaultTableModel model = (DefaultTableModel)lendtable.getModel();
            
           // String selected = model.getValueAt(row, 3).toString();
            
           
        try
        {
            //mysql connection
            String userName = "root";
            String password = "";
            String url      = "jdbc:mysql://localhost:3306/personal_Book_Manager";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection(url, userName, password);
            
            String sql = "DELETE FROM borrowers_list WHERE Name='"+bookname+"'";
            System.out.println(sql);
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            model.removeRow(lendtable.getSelectedRow());
            JOptionPane.showMessageDialog(null, "DONE");
           
        }
        catch(HeadlessException dd)
        {
        } catch (ClassNotFoundException dd) {
        } catch (SQLException dd) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personal_library_GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personal_library_GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personal_library_GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personal_library_GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new personal_library_GUI2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authort;
    private javax.swing.JComboBox bCat;
    private javax.swing.JComboBox bCat1;
    private javax.swing.JPanel backdate;
    private javax.swing.JComboBox combot;
    private javax.swing.JTextField e_mail;
    private javax.swing.JButton exitbtn;
    private com.toedter.calendar.JDateChooser issuedate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lendtable;
    private javax.swing.JTextField namet;
    private javax.swing.JTextField phn_no;
    private com.toedter.calendar.JDateChooser returndate;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton showbtn;
    private javax.swing.JButton srcbtn;
    private javax.swing.JTextField srct;
    // End of variables declaration//GEN-END:variables
}
